CREATE TABLE Mesto(
IdM INT NOT NULL AUTO_INCREMENT,

Mesto VARCHAR(100) NOT NULL,

Vreme_pravljenja DATETIME NOT NULL,

CONSTRAINT pk_mesto PRIMARY KEY (IdM)
);

CREATE TABLE Korisnik(
IdKor INT NOT NULL AUTO_INCREMENT,

Ime VARCHAR(20) NOT NULL,
Prezime VARCHAR(20) NOT NULL,
Mobilni VARCHAR(20) NOT NULL,
Email VARCHAR(40) NOT NULL,
Godiste INT NOT NULL,
Pol CHAR(1) NOT NULL,

IdM INT NOT NULL,

Vreme_pravljenja DATETIME NOT NULL,

CONSTRAINT pk_korisnik PRIMARY KEY (IdKor),
CONSTRAINT fk_korisnik_IdM FOREIGN KEY (IdM) REFERENCES Mesto(IdM)
);

CREATE TABLE Kategorija(
IdKat INT NOT NULL AUTO_INCREMENT,

Naziv VARCHAR(50),

Vreme_pravljenja DATETIME NOT NULL,

CONSTRAINT pk_kategorija PRIMARY KEY (IdKat)
);

CREATE TABLE Artikal(
IdArt INT NOT NULL AUTO_INCREMENT,

Naziv VARCHAR(50) NOT NULL,
Opis VARCHAR(200) NOT NULL,
Cena INT NOT NULL,
Popust INT NOT NULL,
Kolicina INT NOT NULL,

IdKat INT NOT NULL,
IdKor INT NOT NULL,

Vreme_pravljenja DATETIME NOT NULL,

CONSTRAINT pk_artikal PRIMARY KEY(IdArt),
CONSTRAINT fk_artikal_IdKat FOREIGN KEY (IdKat) REFERENCES Kategorija(IdKat),
CONSTRAINT fk_artikal_IdKor FOREIGN KEY (IdKor) REFERENCES Korisnik(IdKor)
);

CREATE TABLE Narudzbina(
IdNar INT NOT NULL AUTO_INCREMENT,

Vreme DATETIME NOT NULL,
Iznos DECIMAL(10,2) NOT NULL,

IdKor INT NOT NULL,

CONSTRAINT pk_narudzbina PRIMARY KEY (IdNar),
CONSTRAINT fk_narudzbina_IdKor FOREIGN KEY (IdKor) REFERENCES Korisnik(IdKor)
);

CREATE TABLE Stavka(
IdNar INT NOT NULL,
IdArt INT NOT NULL,

Iznos DECIMAL(10,2) NOT NULL,
Kolicina INT NOT NULL,

Vreme_pravljenja DATETIME NOT NULL,

CONSTRAINT pk_stavka PRIMARY KEY(IdNar,IdArt),
CONSTRAINT fk_stavka_IdNar FOREIGN KEY (IdNar) REFERENCES Narudzbina(IdNar),
CONSTRAINT fk_stavka_IdArt FOREIGN KEY (IdArt) REFERENCES Artikal(IdArt)
);

CREATE TABLE Korpa(
IdKor INT NOT NULL,
IdArt INT NOT NULL,

Kolicina INT NOT NULL,

Vreme_pravljenja DATETIME NOT NULL,

CONSTRAINT pk_korpa PRIMARY KEY(IdKor, IdArt),
CONSTRAINT fk_korpa_IdKor FOREIGN KEY(IdKor) REFERENCES Korisnik(IdKor),
CONSTRAINT fk_korpa_IdArt FOREIGN KEY(IdArt) REFERENCES Artikal(IdArt)
);

CREATE TABLE Recenzija(
IdKor INT NOT NULL,
IdArt INT NOT NULL,

Ocena INT NOT NULL,
Opis VARCHAR(200) NOT NULL,
Vreme DATETIME NOT NULL,

CONSTRAINT pk_recenzija PRIMARY KEY(IdKor, IdArt),
CONSTRAINT fk_recenzija_IdKor FOREIGN KEY (IdKor) REFERENCES Korisnik(IdKor),
CONSTRAINT fk_recenzija_IdArt FOREIGN KEY (IdArt) REFERENCES Artikal(IdArt)
);
